=== IntersectAustralia/faims-web/lib/assets/data_schema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="term">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" name="description" type="xs:string"/>
        <xs:element maxOccurs="unbounded" minOccurs="0" ref="term"/>
      </xs:sequence>
      <xs:attribute name="semanticMapURL" type="xs:string" use="optional"/>
      <xs:attribute name="pictureURL" type="xs:string" use="optional"/>
      <xs:attribute name="VocabDateFrom" type="xs:string" use="optional"/>
      <xs:attribute name="VocabDateTo" type="xs:string" use="optional"/>
      <xs:attribute name="VocabDateAnnotation" type="xs:string" use="optional"/>
      <xs:attribute name="VocabProvenance" type="xs:string" use="optional"/>
      <xs:attribute name="VocabDateCertainty" type="xs:string" use="optional"/>
      <xs:attribute name="VocabType" type="xs:string" use="optional"/>
      <xs:attribute name="VocabMaker" type="xs:string" use="optional"/>
      <xs:anyAttribute processContents="skip"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="dataSchema">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="RelationshipElement">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="description" type="xs:string"/>
              <xs:element minOccurs="0" name="parent" type="xs:string"/>
              <xs:element minOccurs="0" name="child" type="xs:string"/>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="description" type="xs:string"/>
                    <xs:element minOccurs="0" name="bundle" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="appendCharacterString"/>
                    <xs:element minOccurs="0" name="lookup">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element maxOccurs="unbounded" minOccurs="0" ref="term"/>                          
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" type="xs:string" use="optional"/>
                  <xs:attribute name="name" type="xs:string" use="optional"/>
                  <xs:attribute name="minCardinality" type="xs:byte" use="optional"/>
                  <xs:attribute name="isIdentifier" type="xs:string" use="optional"/>
                  <xs:attribute name="maxCardinality" type="xs:string" use="optional"/>
                  <xs:attribute name="file" type="xs:string" use="optional"/>
                  <xs:attribute name="thumbnail" type="xs:string" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="semanticMapURL" type="xs:string" use="optional"/>
            <xs:attribute name="name" type="xs:string" use="optional"/>
            <xs:attribute name="type" type="xs:string" use="optional"/>
            <xs:anyAttribute processContents="skip"/>
          </xs:complexType>
        </xs:element>
        <xs:element maxOccurs="unbounded" minOccurs="0" name="ArchaeologicalElement">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="description" type="xs:string"/>
              <xs:element maxOccurs="unbounded" minOccurs="0" name="property">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element minOccurs="0" name="description" type="xs:string"/>
                    <xs:element minOccurs="0" name="formatString" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="bundle" type="xs:string"/>
                    <xs:element maxOccurs="unbounded" minOccurs="0" name="appendCharacterString"/>
                    <xs:element minOccurs="0" name="lookup">
                      <xs:complexType>
                        <xs:sequence maxOccurs="unbounded" minOccurs="0">
                          <xs:element maxOccurs="unbounded" minOccurs="0" ref="term"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="type" type="xs:string" use="optional"/>
                  <xs:attribute name="name" type="xs:string" use="optional"/>
                  <xs:attribute name="minCardinality" type="xs:byte" use="optional"/>
                  <xs:attribute name="maxCardinality" type="xs:string" use="optional"/>
                  <xs:attribute name="isIdentifier" type="xs:string" use="optional"/>
                  <xs:attribute name="file" type="xs:string" use="optional"/>
                  <xs:attribute name="thumbnail" type="xs:string" use="optional"/>
                  <xs:anyAttribute processContents="skip"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="semanticMapURL" type="xs:string" use="optional"/>
            <xs:attribute name="name" type="xs:string" use="optional"/>
            <xs:attribute name="type" type="xs:string" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="name" type="xs:string"/>
      <xs:attribute name="preparer" type="xs:string"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== IntersectAustralia/faims-web/spec/assets/data_schema_6.xml
<?xml version="1.0" ?>
<?xml-stylesheet type="text/xsl" href="http://xsd.localdomain/lib/assets/data_schema.xsl"?>
<dataSchema name="ArchitecturalSurvey" preparer="Brian Ballsun.Stanton" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://xsd.localdomain/lib/assets/data_schema.xsd">

<RelationshipElement name="InSurface" type="bidirectional">
	<description>
		foo
	</description>
	<property type="string" name="relnFoo" minCardinality="1" maxCardinality="n">
		<description>
			BAAGGHasdfasdfasdf
		</description>
		<lookup>
			<term pictureURL="files/data/shapes/red.png" semanticMapURL="http://dbpedia.org/resource/Red">
				Red
				<description>
					redstuffs
				</description>
				<term pictureURL="files/data/shapes/red/circle.png">
					Circle
					<description>
						Red circle
					</description>
				</term>
				<term pictureURL="files/data/shapes/red/square.png">
					Square
					<description>
					red square
				</description>
				</term>
				<term pictureURL="files/data/shapes/red/poly.png">
					Polygon
					<description>
					red poly
					</description>
					<term pictureURL="files/data/shapes/red/poly/3.png">
						3-sided
						<description>
							red triangle
						</description>
					</term>
					<term pictureURL="files/data/shapes/red/poly/5.png">
						5-sided
						<description>
							red pentagon
						</description>
					</term>
					<term pictureURL="files/data/shapes/red/poly/6.png">
						6-sided
						<description>
							red hexagon
						</description>
					</term>
					<term pictureURL="files/data/shapes/red/poly/20.png">
						20-sided
						<description>
							red Icosagon
						</description>
					</term>
				</term>
			</term>
		</lookup>
	</property>
</RelationshipElement>
<RelationshipElement name="SurfaceLot" type="bidirectional">
</RelationshipElement>
<RelationshipElement name="WallWith" type="bidirectional">
</RelationshipElement>
<RelationshipElement name="DoorwayIn" type="bidirectional">
</RelationshipElement>
<RelationshipElement name="WindowIn" type="bidirectional">
</RelationshipElement>
<RelationshipElement name="NicheIn" type="bidirectional">
</RelationshipElement>
<RelationshipElement name="LichenAttachedTo" type="bidirectional">
</RelationshipElement>
<RelationshipElement name="StructureContains" type="contains">
</RelationshipElement>
<ArchaeologicalElement type="Structure">
	<property type="string" name="ArchaeologicalElementID" minCardinality="1" maxCardinality="n" isIdentifier="true">
	</property>
	<property type="string" name="Description" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="Timestamp" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="Author" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="Device" minCardinality="1" maxCardinality="n">
		<description>
			BAAGGH
		</description>
		<lookup>
			<term pictureURL="files/data/shapes/red.png" semanticMapURL="http://dbpedia.org/resource/Red">
				Red
				<description>
					redstuffs
				</description>
				<term pictureURL="files/data/shapes/red/circle.png">
					Circle
					<description>
						Red circle
					</description>
				</term>
				<term pictureURL="files/data/shapes/red/square.png">
					Square
					<description>
					red square
				</description>
				</term>
				<term pictureURL="files/data/shapes/red/poly.png">
					Polygon
					<description>
					red poly
					</description>
					<term pictureURL="files/data/shapes/red/poly/3.png">
						3-sided
						<description>
							red triangle
						</description>
					</term>
					<term pictureURL="files/data/shapes/red/poly/5.png">
						5-sided
						<description>
							red pentagon
						</description>
					</term>
					<term pictureURL="files/data/shapes/red/poly/6.png">
						6-sided
						<description>
							red hexagon
						</description>
					</term>
					<term pictureURL="files/data/shapes/red/poly/20.png">
						20-sided
						<description>
							red Icosagon
						</description>
					</term>
				</term>
			</term>
			<term pictureURL="files/data/shapes/green.png" semanticMapURL="http://dbpedia.org/resource/Green">
				Green
				<description>
					greenstuffs
				</description>
				<term pictureURL="files/data/shapes/green/circle.png">
					Circle
				</term>
				<term pictureURL="files/data/shapes/green/square.png">
					Square
				</term>
				<term pictureURL="files/data/shapes/green/poly.png">
					Polygon
					<term pictureURL="files/data/shapes/green/poly/3.png">
						3-sided
						<description>
							triangle
						</description>
					</term>
					<term pictureURL="files/data/shapes/green/poly/5.png">
						5-sided
						<description>
							pentagon
						</description>
					</term>
					<term pictureURL="files/data/shapes/green/poly/6.png">
						6-sided
						<description>
							hexagon
						</description>
					</term>
					<term pictureURL="files/data/shapes/green/poly/20.png">
						20-sided
						<description>
							Icosagon
						</description>
					</term>
				</term>
			</term>
			<term pictureURL="files/data/shapes/blue.png">
				Blue
				<description>
					bluestuffs
				</description>
				<term pictureURL="files/data/shapes/blue/circle.png">
					Circle
				</term>
				<term pictureURL="files/data/shapes/blue/square.png">
					Square
				</term>
				<term pictureURL="files/data/shapes/blue/poly.png">
					Polygon
					<term pictureURL="files/data/shapes/blue/poly/3.png">
						3-sided
						<description>
							triangle
						</description>
					</term>
					<term pictureURL="files/data/shapes/blue/poly/5.png">
						5-sided
						<description>
							pentagon
						</description>
					</term>
					<term pictureURL="files/data/shapes/blue/poly/6.png">
						6-sided
						<description>
							hexagon
						</description>
					</term>
					<term pictureURL="files/data/shapes/blue/poly/20.png">
						20-sided
						<description>
							Icosagon
						</description>
					</term>
				</term>
			</term>
			
		</lookup>
	</property>
	<property type="string" name="Form" minCardinality="1" maxCardinality="n">
		<lookup>
			<term>{Cuadrangular}</term>
			<term>{Ovoide}</term>
			<term>{Circular}</term>
			<term>{zOtro}</term>
		</lookup>
	</property>
	<property type="string" name="FormDescription" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="ConstructionPeriod" minCardinality="1" maxCardinality="n">
		<lookup>
			<term>{Intermedio.Tardio}</term>
			<term>{Horizonte.Tardio}</term>
			<term>{Colonial.Temprano}</term>
			<term>{Colonial.Tardio}</term>
			<term>{zOtro}</term>
		</lookup>
	</property>
	<property type="string" name="ConstructionPeriodDescription" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="Modifications" minCardinality="1" maxCardinality="n">
		<lookup>
			<term>{Yes}</term>
			<term>{No}</term>
			<term>{zNot.Observable}</term>
		</lookup>
	</property>
	<property type="string" name="ModificationDescription" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="PrincipalFunction" minCardinality="1" maxCardinality="n">
		<lookup>
			<term>{Domestica}</term>
			<term>{Almacenaje}</term>
			<term>{Ritual}</term>
			<term>{Administrativa}</term>
			<term>{Funeraria}</term>
			<term>{zOtro}</term>
			<term>{zNo.Definido}</term>
		</lookup>
	</property>
	<property type="string" name="PrincipalFunctionDescription" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="Classification" minCardinality="1" maxCardinality="n">
		<lookup>
			<term>{Casa}</term>
			<term>{Chullpa}</term>
			<term>{Iglesia}</term>
			<term>{Capilla}</term>
			<term>{Kallanka}</term>
			<term>{Posible.Casa.De.Kuraka}</term>
			<term>{Hospital}</term>
			<term>{Cabildo}</term>
			<term>{Carcel}</term>
			<term>{Casa.De.Servicio}</term>
			<term>{Estructura.Asociada}</term>
			<term>{zOtro}</term>
		</lookup>
	</property>
	<property type="string" name="ConstructionQuality" minCardinality="1" maxCardinality="n">
		<lookup>
			<term>{1baja}</term>
			<term>{2}</term>
			<term>{3}</term>
			<term>{4}</term>
			<term>{5alta}</term>
		</lookup>
	</property>
	<property type="string" name="WallsTotalCount" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="WallsGabledCount" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="WallsInternalPartition" minCardinality="1" maxCardinality="n">
		<lookup>
			<term>{0}</term>
			<term>{1}</term>
			<term>{2}</term>
			<term>{3}</term>
			<term>{4}</term>
			<term>{zMore}</term>
			<term>{zNo.Observable}</term>
		</lookup>
	</property>
	<property type="string" name="PartitionDescription" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="StuccoInterior" minCardinality="1" maxCardinality="n">
		<lookup>
			<term>{Yes}</term>
			<term>{No}</term>
			<term>{zNot.Observable}</term>
		</lookup>
	</property>
	<property type="string" name="StuccoExterior" minCardinality="1" maxCardinality="n">
		<lookup>
			<term>{Yes}</term>
			<term>{No}</term>
			<term>{zNot.Observable}</term>
		</lookup>
	</property>
	<property type="string" name="WindowCount" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="DoorwayCount" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="NicheCount" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="FloorRemainsDescription" minCardinality="1" maxCardinality="n">
	</property>
	<property type="string" name="RoofForm" minCardinality="1" maxCardinality="n">
		<lookup>
			<term>{Hastial.Dos.Aguas}</term>
			<term>{Hastial.Un.Agua}</term>
			<term>{Sin.Hastial}</term>
			<term>{zOtro}</term>
			<term>{zNo.Observable}</term>
		</lookup>
	</property>
	<property type="string" name="LongAxis" minCardinality="1" maxCardinality="n">
	</property>
